<?php 
include 'koneksi.php';
$IDPRODUCT=$_POST['IDPRODUCT'];
$IDTYPEOFPRODUCT=$_POST['IDTYPEOFPRODUCT'];
$NAMEOFPRODUCT=$_POST['NAMEOFPRODUCT'];
$GOODORSERVICE=$_POST['GOODORSERVICE'];

$ubah= "UPDATE tsilabtan_product SET IDTYPEOFPRODUCT='".$IDTYPEOFPRODUCT."',NAMEOFPRODUCT='".$NAMEOFPRODUCT."',GOODORSERVICE='".$GOODORSERVICE."' WHERE IDPRODUCT='".$IDPRODUCT."'";
mysql_query($ubah); 
header("location:index.php?page=tabel_product");
?>